project:
  type: website
  output-dir: docs

website:
  title: "Mohan Khanal"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "R Tutorials"
        menu:
          - href: r-tutorial/RBasics.qmd
            text: "1: R Basics"
          - href: r-tutorial/2DataImportandDataWrangling.qmd
            text: "2: Data Import & Wrangling"
          - href: r-tutorial/3ExploratoryDataAnalysis.qmd
            text: "3: Exploratory Data Analysis"
          - href: r-tutorial/4StatisticalAnalysis.qmd
            text: "4: Statistical Analysis"
      - href: mascollelmicroeconomics/Part1.qmd
        text: Microeconomics

  sidebar:
    - id: rtutorials
      title: "R Tutorial for Data Science"
      contents:
        - r-tutorial/RBasics.qmd
        - r-tutorial/2DataImportandDataWrangling.qmd
        - r-tutorial/3ExploratoryDataAnalysis.qmd
        - r-tutorial/4StatisticalAnalysis.qmd

    - id: micro
      title: "Mas-Colell Microeconomics"
      contents:
        - mascollelmicroeconomics/Part1.qmd

  page-navigation: true